### ISSUE TITLE
NPE CommentActivity$OnDeleteMeasurement

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#100]
```
java.lang.NullPointerException
	at org.noise_planet.noisecapture.CommentActivity$OnDeleteMeasurement$1.onClick(CommentActivity.java:393)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)
```

Version de l'application
 
19
Version d'Android
 
Android 4.4
Appareil
Galaxy Note (GT-N7000)

**Comment by pierromond** [comment]
Close ?
