### ISSUE TITLE
WPS parse exception

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#277]
```
org.geotools.process.ProcessException: javax.script.ScriptException: java.util.zip.ZipException: invalid entry size (expected 2231000 but got 2230395 bytes)
	at org.geoserver.script.wps.ScriptProcess.execute(ScriptProcess.java:121)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:51)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:201)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:169)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.script.ScriptException: java.util.zip.ZipException: invalid entry size (expected 2231000 but got 2230395 bytes)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImpl(GroovyScriptEngineImpl.java:405)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeFunction(GroovyScriptEngineImpl.java:200)
	at org.geoserver.script.ScriptHook.doInvoke(ScriptHook.java:76)
	at org.geoserver.script.ScriptHook.invoke(ScriptHook.java:60)
	at org.geoserver.script.wps.WpsHook.run(WpsHook.java:187)
	at org.geoserver.script.groovy.GroovyWpsHook.run(GroovyWpsHook.java:41)
	at org.geoserver.script.wps.ScriptProcess.execute(ScriptProcess.java:119)
	... 7 more
Caused by: java.util.zip.ZipException: invalid entry size (expected 2231000 but got 2230395 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:384)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at java_util_zip_ZipInputStream$getNextEntry.call(Unknown Source)
	at org.noise_planet.noisecapturegs.Script16$_processFile_closure1.doCall(Script16.groovy:92)
	at sun.reflect.GeneratedMethodAccessor892.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1207)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1674)
	at org.codehaus.groovy.runtime.dgm$1019.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.noise_planet.noisecapturegs.Script16.processFile(Script16.groovy:89)
	at org.noise_planet.noisecapturegs.Script16$processFile$1.callStatic(Unknown Source)
	at org.noise_planet.noisecapturegs.Script16.processFiles(Script16.groovy:327)
	at org.noise_planet.noisecapturegs.Script16$processFiles$0.callStatic(Unknown Source)
	at org.noise_planet.noisecapturegs.Script16.run(Script16.groovy:382)
	at sun.reflect.GeneratedMethodAccessor424.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:417)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:411)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImpl(GroovyScriptEngineImpl.java:400)
	... 13 more
```

**Comment by nicolas-f** [comment]
Fixed
