### ISSUE TITLE
Can't sent data to cloud

### ISSUE THREAD

**Issue by baudav** [Ifsttar/NoiseCapture#297]
Hi,
I can't sent data to cloud with error: Cleartext HTTP traffic to onomap-gs.noise-planet.org not permitted
Same error if transfert from history.

![image](https://user-images.githubusercontent.com/10183995/53686910-d3569400-3d2d-11e9-8f29-b4a63c893a46.png)

**Comment by nicolas-f** [comment]
Thanks for the feedback, fix in the pipes

**Comment by nicolas-f** [comment]
Fix released in Beta version (v  1.2.8).

Please let us know if it works on your device. Thanks

**Comment by baudav** [comment]
no, it's not work. apps crash:
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
	at org.noise_planet.noisecapture.MeasurementExport.recordsToGeoJSON(MeasurementExport.java:131)
	at org.noise_planet.noisecapture.MeasurementExport.exportRecord(MeasurementExport.java:237)
	at org.noise_planet.noisecapture.MeasurementUploadWPS.uploadRecord(MeasurementUploadWPS.java:95)
	at org.noise_planet.noisecapture.MainActivity$SendZipToServer.run(MainActivity.java:671)
	at java.lang.Thread.run(Thread.java:764)

**Comment by baudav** [comment]
ok, the new beta (1.2.9 22mars) work fine.

**Comment by baudav** [comment]
KO this day. app not crash but bottom notification say 'Chain validation failed'

certificat chain ?

**Comment by nicolas-f** [comment]
Hi,

Thanks for the feedback, there was a server migration errors.

It should be fixed now

**Comment by baudav** [comment]
Hi,
yes it's fixed. thanks
