### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#66]
```
java.lang.IllegalStateException: no included points
	at com.google.android.gms.common.internal.zzaa.zza(Unknown Source)
	at com.google.android.gms.maps.model.LatLngBounds$Builder.build(Unknown Source)
	at org.noise_planet.noisecapture.MapActivity.loadWebView(MapActivity.java:125)
	at org.noise_planet.noisecapture.MapActivity$MapDropDownChooseListener.onItemSelected(MapActivity.java:206)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:1165)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1154)
	at android.widget.AdapterView.access$300(AdapterView.java:59)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1121)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by nicolas-f** [comment]
l'appli se ferme seule quand on veut aller sur community sound map. 

Appareil
Galaxy S5 (klte) 1
Fabricant Samsung Version d'Android Android 4.0.3 - 4.0.4 RAM (Mo) 2048 Taille de l'écran 1080 × 1920 Densité d'écran (ppp) 480 Version OpenGL ES 3.0 Plate-forme native armeabi-v7a Marque du processeur Qualcomm Modèle du processeur MSM8974

**Comment by nicolas-f** [comment]
Fixed

**Comment by samprathyusha** [comment]
how the above error is fixed
