### ISSUE TITLE
Crash on landscape mode on comment activity

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#91]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.noise_planet.noisecapture/org.noise_planet.noisecapture.CommentActivity}: java.lang.ClassCastException: android.support.v7.widget.AppCompatImageButton cannot be cast to android.widget.Button
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4203)
	at android.app.ActivityThread.access$900(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5624)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.lang.ClassCastException: android.support.v7.widget.AppCompatImageButton cannot be cast to android.widget.Button
	at org.noise_planet.noisecapture.CommentActivity.onCreate(CommentActivity.java:119)
	at android.app.Activity.performCreate(Activity.java:6128)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
	... 11 more
```

**Comment by nicolas-f** [comment]
Fixed
